import PDFDocument from "pdfkit";

export const generatePDF = (result, res) => {

  const doc = new PDFDocument({
    size: "A4",
    margin: 50
  });

  res.setHeader("Content-Type", "application/pdf");
  res.setHeader(
    "Content-Disposition",
    `attachment; filename=AI_Interview_Report_${Date.now()}.pdf`
  );

  doc.pipe(res);

  // ===============================
  // HEADER
  // ===============================
  doc
    .rect(0, 0, 595, 80)
    .fill("#4f46e5");

  doc
    .fillColor("#ffffff")
    .fontSize(24)
    .text("AI Interview Performance Report", 50, 30, {
      align: "center"
    });

  doc.moveDown(4);

  // ===============================
  // CANDIDATE SUMMARY
  // ===============================
  doc
    .fillColor("#000")
    .fontSize(14)
    .text("Interview Summary", { underline: true });

  doc.moveDown();

  doc.fontSize(12)
    .text(`Date: ${new Date().toLocaleDateString()}`)
    .text(`Interview Score: ${result.score}/100`);

  doc.moveDown(2);

  // ===============================
  // SCORE BOX
  // ===============================
  doc
    .roundedRect(50, 200, 500, 70, 10)
    .fill("#ecfdf5");

  doc
    .fillColor("#065f46")
    .fontSize(20)
    .text(`Total Score: ${result.score}/100`, 50, 225, {
      align: "center"
    });

  doc.moveDown(5);

  // ===============================
  // PERFORMANCE TABLE
  // ===============================
  const startY = 320;

  doc
    .fillColor("#000")
    .fontSize(14)
    .text("Performance Breakdown", 50, startY);

  const tableTop = startY + 30;

  const breakdown = [
    ["Skill", "Score"],
    ["Communication", result.breakdown.communication],
    ["Technical", result.breakdown.technical],
    ["Confidence", result.breakdown.confidence]
  ];

  let y = tableTop;

  breakdown.forEach((row, i) => {

    const isHeader = i === 0;

    doc
      .rect(50, y, 250, 30)
      .stroke();

    doc
      .rect(300, y, 250, 30)
      .stroke();

    doc
      .fontSize(12)
      .fillColor(isHeader ? "#4f46e5" : "#000")
      .text(row[0], 60, y + 8);

    doc
      .text(row[1].toString(), 310, y + 8);

    y += 30;

  });

  // ===============================
  // AI FEEDBACK
  // ===============================
  doc.moveDown(4);

  doc
    .fillColor("#000")
    .fontSize(14)
    .text("AI Feedback", 50, y + 20, {
      underline: true
    });

  doc
    .fontSize(12)
    .text(result.feedback, 50, y + 50, {
      width: 500,
      align: "justify"
    });

  // ===============================
  // FOOTER
  // ===============================
  doc
    .fontSize(10)
    .fillColor("#6b7280")
    .text(
      "Generated by AI Career Guidance System",
      50,
      750,
      { align: "center", width: 500 }
    );

  doc.end();
};